More updates for production
- add settings for source db and destination ES node
- update libraries
- improve documentation
- handle differences between ES 6 and 7
- log errors during ES operations

diff --git a/import-es b/import-es
--- a/import-es
+++ b/import-es
@@ -1,31 +1,49 @@
 #!/bin/sh
 
+set +x
+
 ENV=$1
 DELETEDATA=$2
+
+# Default to 'cdev' db.
+export DB_HOST=nodes.nonprod.kube.tstllc.net
+export DB_PORT=32114
+# export DB_HOST=mysqlread.prod.infra.tstllc.net
+# export DB_PORT=3306
+
+export ES_HOST=nodes.lower.kube.tstllc.net
+export ES_PORT=32200
+# export ES_HOST=nodes.prodint.kube.tstllc.net
+# export ES_PORT=32200
+
+# TODO: Get these from secrets.
+export DB_USER=root
+export DB_PASS=kube-aws
+# export DB_USER=support_ro
+# export DB_PASS="1mdsupp0rtp3rs0n!"
+
+if ! nc -z "$ES_HOST" "$ES_PORT"; then
+  echo "Could not connect to ElasticSearch host $ES_HOST:$ES_PORT"
+  exit
+fi
 
 echo "Targeting Elastic Search data for $ENV"
 
 if [ -n "$DELETEDATA" ]; then
   echo "Deleting data...."
-  echo "NB: At this time you must have local port 8000"
-  echo "to the targeted elastic search node."
-  # TODO: Use the correct endpoint here.
-  curl -i -XDELETE http\://localhost\:8000/booking-$ENV
+  ES_URL="http://$ES_HOST:$ES_PORT/booking-$ENV"
+  echo $ES_URL
+  curl -i -XDELETE "$ES_URL"
   echo
   echo "Done."
 fi
 
-# Default to 'cdev' db.
-export DB_HOST=nodes.nonprod.kube.tstllc.net
-export DB_PORT=32114
-
-# TODO: Get these from secrets.
-export DB_USER=root
-export DB_PASS=kube-aws
-
-YEARS=$(seq 2010 2020)
+YEARS=$(seq 2018 2020)
 
 for YEAR in $YEARS; do
-  echo "Importing data from $YEAR"
-  java -jar app-standalone.jar $ENV $YEAR
+  MONTHS=$(seq 1 12)
+  for MONTH in $MONTHS; do
+    echo "Importing data from $YEAR $MONTH"
+    java -jar app-standalone.jar $ENV $YEAR $MONTH
+  done
 done
